### ISSUE TITLE
Error during install on a rpi3 A+

### ISSUE THREAD

**Issue by remiDubois2304** [KenT2/pipresents-kms#13]
Hello,
I have managed to install pipresents gapless on a pi3 model A+ but today I'm struggling to install kms and make it work on this model. After a few tried, I end up with an error when launching pipresents to test if the install is OK (the step before installing the profiles). 

Package install went well, image was flashed with pi imager.

I'll put below the logs from terminal when asking the command "python3 /home/pi/pipresents/pipresents.py"

If anyone can help me, I don't know if I missed something or if this is related to the A+.

Thanks a lot

python3 /home/pi/pipresents/pipresents.py
Traceback (most recent call last):
  File "/home/pi/pipresents/pipresents.py", line 31, in <module>
    from pp_showmanager import ShowManager
  File "/home/pi/pipresents/pp_showmanager.py", line 350, in <module>
    from pp_menushow import MenuShow
  File "/home/pi/pipresents/pp_menushow.py", line 4, in <module>
    from pp_show import Show
  File "/home/pi/pipresents/pp_show.py", line 15, in <module>
    from pp_chromeplayer import ChromePlayer
  File "/home/pi/pipresents/pp_chromeplayer.py", line 6, in <module>
    from selenium import webdriver
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/__init__.py", line 20, in <module>
    from .chrome.webdriver import WebDriver as Chrome  # noqa
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chrome/webdriver.py", line 18, in <module>
    from selenium.webdriver.chromium.webdriver import ChromiumDriver
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chromium/webdriver.py", line 22, in <module>
    from selenium.webdriver.remote.webdriver import WebDriver as RemoteWebDriver
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 67, in <module>
    from .websocket_connection import WebSocketConnection
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/websocket_connection.py", line 23, in <module>
    from websocket import WebSocketApp
ModuleNotFoundError: No module named 'websocket'

**Comment by KenT2** [comment]
It looks like you have not installed selenium. Another possibility - You are not  using RPi OS Bullseye 32 bit with desktop

**Comment by remiDubois2304** [comment]
Thank you for your reply, i'll try a new install soon.

Also, thank you for this wonderful tool, pipresents is such a powerful software.

**Comment by remiDubois2304** [comment]
It's OK, I've messed up with two versions and two different manuals... sorry about that !
