### ISSUE TITLE
error while starting the media show example from the github kent2

### ISSUE THREAD

**Issue by crazysid44** [KenT2/pipresents-kms#7]
From the terminal window type:

     python3 /home/<username>/pipresents/pipresents.py -p pp_mediashow_1p5

i got this:

$ python3 /home/crazysid/pipresents/pipresents.py -p pp_mediashow_1p5
Traceback (most recent call last):
  File "/home/crazysid/pipresents/pipresents.py", line 31, in <module>
    from pp_showmanager import ShowManager
  File "/home/crazysid/pipresents/pp_showmanager.py", line 350, in <module>
    from pp_menushow import MenuShow
  File "/home/crazysid/pipresents/pp_menushow.py", line 4, in <module>
    from pp_show import Show
  File "/home/crazysid/pipresents/pp_show.py", line 7, in <module>
    from PIL import ImageTk
ImportError: cannot import name 'ImageTk' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)

**Comment by KenT2** [comment]
You probaably forgot this in installation

sudo apt install python3-pil.imagetk
